spring:
  datasource:
    url:jdbc:mysql://localhost:3306/testmybatis?useSSL=false
    username:root
    password:my6291015

jpa:
  hibernate:
    ddl-auto: update
  database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  show-sql: true